### ISSUE TITLE
ValueError: empty range for randrange() (0,-139, -139)

### ISSUE THREAD

**Issue by xinfu607** [dvornikita/fewshot_ensemble#2]
python ensembles/train.py --model.model_name=deep_robust10 --data.dataset=mini_imagenet --model.backbone=deep --ens.num_heads=10 --ens.relation_type=robust

 !!!!!! Starting ephoch 0 !!!!!!
  0%|                                                  | 0/2400 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/xinfu/code/few_shot_learning/fewshot_ensemble/ensembles/train.py", line 178, in <module>
    main()
  File "/xinfu/code/few_shot_learning/fewshot_ensemble/ensembles/train.py", line 62, in main
    for i, sample in enumerate(tqdm(train_sampler)):
  File "/opt/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 339, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 360, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/xinfu/code/few_shot_learning/fewshot_ensemble/data/datasets.py", line 60, in __getitem__
    img = self.transform(img)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 421, in __call__
    i, j, h, w = self.get_params(img, self.size)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 399, in get_params
    i = random.randint(0, h - th)
  File "/opt/conda/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/opt/conda/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-139, -139)

The error occurrs while running the program. Would you please tell me the reason?

**Comment by dvornikita** [comment]
Hi,

The code fails when you try to make a random crop of size 224x224. It means that your input image is smaller than this. Perhaps you use 84x84 images as input.

I updated the code to work in this case and pushed the modifications. However, the results you obtain will be different from the ones reported in the paper.

Let me know if it works now.

**Comment by dvornikita** [comment]
Closing due to the lack of recent activity.
